"""
utils/pdf_generator.py
Converts generated markdown documentation into a styled, downloadable PDF
using reportlab Platypus.
"""
import io
import re
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    HRFlowable, Preformatted,
)
from reportlab.lib.enums import TA_LEFT

PRIMARY  = HexColor("#0f172a")
ACCENT   = HexColor("#6366f1")
MUTED    = HexColor("#64748b")
CODE_BG  = HexColor("#f1f5f9")
CODE_FG  = HexColor("#0f172a")
RULE     = HexColor("#e2e8f0")
BODY_FG  = HexColor("#334155")


def _styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("DocTitle", parent=base["Normal"],
            fontSize=28, leading=34, textColor=PRIMARY, spaceAfter=4,
            fontName="Helvetica-Bold", alignment=TA_LEFT),
        "subtitle": ParagraphStyle("DocSubtitle", parent=base["Normal"],
            fontSize=12, leading=17, textColor=MUTED, spaceAfter=4,
            fontName="Helvetica"),
        "meta": ParagraphStyle("Meta", parent=base["Normal"],
            fontSize=9, leading=13, textColor=MUTED, fontName="Helvetica"),
        "h1": ParagraphStyle("H1", parent=base["Normal"],
            fontSize=20, leading=26, textColor=PRIMARY,
            spaceBefore=20, spaceAfter=6, fontName="Helvetica-Bold"),
        "h2": ParagraphStyle("H2", parent=base["Normal"],
            fontSize=15, leading=20, textColor=ACCENT,
            spaceBefore=16, spaceAfter=4, fontName="Helvetica-Bold"),
        "h3": ParagraphStyle("H3", parent=base["Normal"],
            fontSize=12, leading=16, textColor=PRIMARY,
            spaceBefore=10, spaceAfter=3, fontName="Helvetica-Bold"),
        "body": ParagraphStyle("Body", parent=base["Normal"],
            fontSize=10, leading=15, textColor=BODY_FG,
            spaceAfter=6, fontName="Helvetica"),
        "bullet": ParagraphStyle("Bullet", parent=base["Normal"],
            fontSize=10, leading=14, textColor=BODY_FG,
            spaceAfter=3, leftIndent=16, fontName="Helvetica"),
        "code": ParagraphStyle("Code", parent=base["Code"],
            fontSize=8, leading=12, textColor=CODE_FG, backColor=CODE_BG,
            fontName="Courier", leftIndent=10, rightIndent=10,
            spaceBefore=4, spaceAfter=8,
            borderPadding=(6, 8, 6, 8)),
    }


def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4
    canvas.setStrokeColor(RULE)
    canvas.setLineWidth(0.5)
    canvas.line(18*mm, h - 14*mm, w - 18*mm, h - 14*mm)
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    canvas.drawString(18*mm, 11*mm, "Generated by Doc Generator Agent · Powered by Gemma")
    canvas.drawRightString(w - 18*mm, 11*mm,
        f"Page {doc.page}  ·  {datetime.now().strftime('%Y-%m-%d')}")
    canvas.restoreState()


def _inline(text: str) -> str:
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    text = re.sub(r"__(.+?)__",     r"<b>\1</b>", text)
    text = re.sub(r"\*(.+?)\*",     r"<i>\1</i>", text)
    text = re.sub(r"`(.+?)`", r'<font name="Courier" size="9">\1</font>', text)
    return text


def _parse(markdown: str, s: dict) -> list:
    story, lines, i = [], markdown.split("\n"), 0
    while i < len(lines):
        line = lines[i]
        if line.strip().startswith("```"):
            code_lines = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith("```"):
                code_lines.append(lines[i])
                i += 1
            story.append(Preformatted("\n".join(code_lines), s["code"]))
            i += 1; continue
        if line.startswith("### "): story.append(Paragraph(_inline(line[4:]), s["h3"])); i += 1; continue
        if line.startswith("## "):
            story.append(Paragraph(_inline(line[3:]), s["h2"]))
            story.append(HRFlowable(width="100%", thickness=0.4, color=ACCENT, spaceAfter=3))
            i += 1; continue
        if line.startswith("# "): story.append(Paragraph(_inline(line[2:]), s["h1"])); i += 1; continue
        if line.startswith(("- ", "* ", "+ ")):
            story.append(Paragraph("•  " + _inline(line[2:]), s["bullet"])); i += 1; continue
        m = re.match(r"^(\d+)\.\s+(.*)", line)
        if m:
            story.append(Paragraph(f"{m.group(1)}.  " + _inline(m.group(2)), s["bullet"])); i += 1; continue
        if line.strip() == "": story.append(Spacer(1, 4)); i += 1; continue
        if line.strip() in ("---", "***", "___"):
            story.append(HRFlowable(width="100%", thickness=0.4, color=RULE, spaceAfter=5)); i += 1; continue
        story.append(Paragraph(_inline(line), s["body"])); i += 1
    return story


def generate_pdf(title: str, description: str, repo_url: str, markdown_content: str) -> bytes:
    buf = io.BytesIO()
    s   = _styles()

    doc = SimpleDocTemplate(buf, pagesize=A4,
        leftMargin=18*mm, rightMargin=18*mm,
        topMargin=22*mm,  bottomMargin=22*mm,
        title=title, author="Doc Generator Agent", subject=description)

    story = [
        Spacer(1, 8*mm),
        Paragraph(title, s["title"]),
        Spacer(1, 2),
        Paragraph(description, s["subtitle"]),
        Spacer(1, 2),
        Paragraph(f'<font name="Courier" size="9" color="#6366f1">{repo_url}</font>', s["meta"]),
        Paragraph(f'Generated: {datetime.now().strftime("%B %d, %Y at %H:%M")}', s["meta"]),
        Spacer(1, 6),
        HRFlowable(width="100%", thickness=2, color=ACCENT, spaceAfter=14),
    ]
    story.extend(_parse(markdown_content, s))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    buf.seek(0)
    return buf.getvalue()